### ISSUE TITLE
BLAS (subissue of [#1](https://github.com/yctai1994/PhysInfoNN.zig/issues/1))

### ISSUE THREAD

**Issue by yctai1994** [yctai1994/PhysInfoNN.zig#3]
### Level 1
- [ ] `scal`: $x \leftarrow a x$
- [ ] `copy`: $y \leftarrow x$
- [ ] `axpy`: $y \leftarrow a x + y$
- [ ] `xoty`: $y \leftarrow x \otimes y$
### Level 2
- [ ] `gemv`: $y \leftarrow a A x + b y$, $y \leftarrow a A^{\intercal} x + b y$
- [ ] `geru`: $A \leftarrow a x y^{\intercal}$
